version: "3.7"
services:
    Nest-Vocab:
        build: .
        ports:
            - "3001:3001"
        volumes:
            - ".:/app"
            - "/app/node_modules"
            - "./oracle/wallet:/opt/oracle/instantclient_19_10/network/admin"
        image: nest-vocab
        environment:
            LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_10"
        container_name: nest-vocab-dev
    redis:
        restart: always
        container_name: redis
        image: redis:alpine
        ports:
            - "127.0.0.1:6379:6379"
        command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
